### ISSUE TITLE
Shift+space transfer not working in barrels (maybe chests too idk)

### ISSUE THREAD

**Issue by AdnanuReeves** [deletey/CompactStorage#100]
So I use the mod https://www.curseforge.com/minecraft/mc-mods/inventory-essentials which allows for transfering everything by using shift+space click and it works for every inventory except for the ones from this mod.. can you fix that so it works by any chance? I love your mod and would really like to use it.. but thats a big annoyance for me :(

it works when taking out of the barrels, but not in.

**Comment by witchica** [comment]
Let me look at this tomorrow and I'll get back to you. It's strange that it doesn't work

**Comment by witchica** [comment]
https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3209571

**Comment by AdnanuReeves** [comment]
Woah, didn't expect you to respond that quick, and fix it so damn fast nevertheless. Thank you so much! :)
