### ISSUE TITLE
Inventory blanks when opening backpack, shows in backpack until relog

### ISSUE THREAD

**Issue by Varijon** [deletey/CompactStorage#101]
User reported the following bug:
[Before opening](https://cdn.discordapp.com/attachments/810349274126090241/813316179920683028/2021-02-22_08.44.07.png)
[After opening](https://cdn.discordapp.com/attachments/810349274126090241/813316175336833044/2021-02-22_08.41.41.png)

**Comment by witchica** [comment]
Certainly an odd one! I'll look into this tomorrow :)

**Comment by witchica** [comment]
@Varijon what version of mod is on the client and server? There was recently an update to how slots work and I'm thinking a version mismatch might be causing this

**Comment by Varijon** [comment]
It was with "compactstorage-1.16.5-5.1b16", but I'm asking people if it happens more often or is just a rare occurrence. Did not provide much to go off with this issue, sorry about that.

**Comment by Varijon** [comment]
I got a reply from the people having issues, they were indeed using the older version. Sorry about that, closing issue.
