### ISSUE TITLE
Consider merging the column and row upgrades into a single item

### ISSUE THREAD

**Issue by TheDeviantCrafter** [deletey/CompactStorage#104]
This new item would alternate between adding rows and columns. I can't think of a situation where I would want to expand one but not the other.

**Comment by zanecek** [comment]
It's not a good idea.
I need high but narrow inventory (due to JEI).

**Comment by witchica** [comment]
It's a design choice of the mod and merging them limits what people can do with it, a compromise would be to add an upgrade that does both?
