### ISSUE TITLE
Item Dupe issue

### ISSUE THREAD

**Issue by wwaisath** [deletey/CompactStorage#105]
When I shift-right-click on the first item (upper left corner), it doubles the item's quantity and moves it to the next available space. It only happens in this one spot, and it happens every time I try it, no matter what storage I am using (chest, barrel, or backpack).

I am using the most current version of CompactStorage (Forge 1.16.5 5.1b16), with Forge 36.0.46, no modifications to the mod config file. It also did this with Forge 36.0.44 - I did not try with 36.0.45 as I skipped it.

**Comment by Wxrlds** [comment]
Can confirm this, also happens to me with Shift + Left Click and Shift + Right Click
Only mods used are:
Forge 36.0.43
jei-1.16.4-7.6.1.71
compactstorage-1.16.5-5.1b16

**Comment by witchica** [comment]
https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3235988
