### ISSUE TITLE
Chest/barrel duplication with Packing Tape mod

### ISSUE THREAD

**Issue by zanecek** [deletey/CompactStorage#106]
When I want transfer compact chest/barrel with Packing Tape mod utility,
https://www.curseforge.com/minecraft/mc-mods/packing-tape
the chest/barrel is duplicated - the second drops around (without content).

**Comment by CKY-** [comment]
include bag of yurting to this 
https://www.curseforge.com/minecraft/mc-mods/bag-of-yurting
the chest/barrel is duplicated - the second drops around (without content).

**Comment by witchica** [comment]
Fixed in 1.19
