### ISSUE TITLE
Add Tags For BackPack and Barrel

### ISSUE THREAD

**Issue by MickeyMouseYT** [deletey/CompactStorage#114]
Please add tags for backpack and barrel :

#compactstorage:compact_barrel
- compactstorage:compact_barrel_black
- compactstorage:compact_barrel_blue
- compactstorage:compact_barrel_brown
- compactstorage:compact_barrel_cyan
- compactstorage:compact_barrel_gray
- compactstorage:compact_barrel_green
- compactstorage:compact_barrel_light_blue
- compactstorage:compact_barrel_light_grey
- compactstorage:compact_barrel_lime
- compactstorage:compact_barrel_magenta
- compactstorage:compact_barrel_orange
- compactstorage:compact_barrel_pink
- compactstorage:compact_barrel_purple
- compactstorage:compact_barrel_red
- compactstorage:compact_barrel_white
- compactstorage:compact_barrel_yellow

#compactstorage:backpack
- compactstorage:backpack_black
- compactstorage:backpack_blue
- compactstorage:backpack_brown
- compactstorage:backpack_cyan
- compactstorage:backpack_gray
- compactstorage:backpack_green
- compactstorage:backpack_light_blue
- compactstorage:backpack_light_grey
- compactstorage:backpack_lime
- compactstorage:backpack_magenta
- compactstorage:backpack_orange
- compactstorage:backpack_pink
- compactstorage:backpack_purple
- compactstorage:backpack_red
- compactstorage:backpack_white
- compactstorage:backpack_yellow

Thank you.

**Comment by witchica** [comment]
Done in new versions!
