### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Rithenar** [deletey/CompactStorage#116]
Is there a way to empty backpacks directly onto another inventory through something similar to shift+right click? Also, is there anything that can make the backpacks auto pickup? Playing Skyfactory 4.

**Comment by witchica** [comment]
Auto pickup is an interesting feature idea I have been looking at for a while! I might try that in the new version, as for the unloading unfortunately not I don't think. Both are great ideas and I'll have a look at adding them
