### ISSUE TITLE
Backpack not opening anymore

### ISSUE THREAD

**Issue by Rasenwish89** [deletey/CompactStorage#117]
Hi, I'm playing minecraft 1.16.3 with Fabric (the specific version of this mod is "compact-storage-4.1.0-1.16.2").
Everything worked perfectly fine with this mod, until today. My backpack (with all my items stored) doesn't open anymore (any other backpack works fine). Could it be that I stored too many items inside, surpassing the limit allowed?
Inside my (fully upgraded) backpack I had many other completely filled up (and fully upgraded) backpacks, so that i could live a nomadic life bringing with me only one storage solution.
How can I retrieve my items, or alternatively, how can I fix this issue?

**Comment by witchica** [comment]
Have you got a log file?
