### ISSUE TITLE
Duplicated Backpacks

### ISSUE THREAD

**Issue by Rupros14** [deletey/CompactStorage#120]
Ihave this backpack that is color black and the width is 11 and the height is 9 and this another bag that is color blue that has a with of 13 and a height of 9. While i was playing on a server when i checked my blue bag it was the same with the black bag on my hotbar so i was wondering how do you fix that? i meam i have diamonds in it hehe so i just want to know the reason

**Comment by witchica** [comment]
Not too sure but seems like there is a bug in the opening of the backpack, looking into it
