### ISSUE TITLE
Item dupe has returned!

### ISSUE THREAD

**Issue by OTCephalus** [deletey/CompactStorage#122]
On 1.16.5 latest version it seems have two backpacks of the same grade on hotbar with stuff in one and not the other you can dupe so they have the same items. Let’s say backpack with stuff is slot 2 and with no stuff slot 3. If you hover over backpack in #3 with #2 open and press 2 it’ll dupe the items in #2 to the #3 backpack you tried moving. Sorry if that was confusing to explain.

**Comment by thomas-vitre** [comment]
#128 Duplication with the backpack but another way

**Comment by witchica** [comment]
Getting on fixing this one :)
