### ISSUE TITLE
Creates NBT Tag When Picked Up A Second Time

### ISSUE THREAD

**Issue by yancypro** [deletey/CompactStorage#123]
I created 4 purple compact chests, picked them up and put them away in their 9x3 state. Then later, got one out, put it on the floor to add rows and columns to it but had to do something else first. So I picked it up and went to put it with the others as it was before and they would not stack because this one now had an NBT Tag assigned to it. I didn't do anything but put it down and pick it back up to create this tag, so now I need to know how to clear this NBT Tag so it will stack with the others of its likeness. I have attached 4 screenshots so you can see the comparisons.
1. This is the 3 base types (without CTRL description) - No "NBT Tag"
![image](https://user-images.githubusercontent.com/65453692/155776758-705bf2b4-981f-4dc3-8445-73faa3e06b13.png)
2. This is the 3 base types (with CTRL description)
![image](https://user-images.githubusercontent.com/65453692/155777410-8b865d55-981f-45a6-80b2-80f1f2502577.png)
3. This is the 1 after second pickup (without CTRL description) With "NBT: 1 Tag(s)"
![image](https://user-images.githubusercontent.com/65453692/155778001-4a3a85b4-39a8-42bc-96b5-afe4cc7287c8.png)
4. This is the 1 after second pickup (with CTRL description)
![image](https://user-images.githubusercontent.com/65453692/155778324-ff3770a7-1346-464c-818e-2249995343d4.png)

**How do I clear this NBT Tag?**
Thanks!

**Comment by witchica** [comment]
This is a bug and is fixed in the new verison releasing today!
