### ISSUE TITLE
ALSO Won't Keep Name Assigned On Anvil

### ISSUE THREAD

**Issue by yancypro** [deletey/CompactStorage#124]
Also, assigned a name to the chest "Mystical Agriculture" on the Anvil. Then I placed it on the floor and the name changed back to the default "Purple Compact Chest" name. See Screenshots:
![image](https://user-images.githubusercontent.com/65453692/155786089-9cfcc25b-cc30-4837-b67e-0d6b927438c6.png)

![image](https://user-images.githubusercontent.com/65453692/155786129-d7a2fd2d-73a3-48d8-a012-28fa46d082a2.png)

**Comment by witchica** [comment]
This is a bug in the renaming, I'll fix that :)
