### ISSUE TITLE
Dupe Bug With Backpack

### ISSUE THREAD

**Issue by thomas-vitre** [deletey/CompactStorage#128]
Hi,
I juste find a dupe bug in wour mod with the backpack

to try the bug :
1. Take in your off hand the backpack with item inside
2. Press "F" keyboard and drop the backpack
3. Take all item in your backpack GUI
4. Close the backpack and take the dropped backpack and open 

Version of the mod  `Forge 1.16.5 5.1b17`

**Comment by witchica** [comment]
I'll look into this!
