### ISSUE TITLE
Does the backpack wearable?

### ISSUE THREAD

**Issue by ardissaps** [deletey/CompactStorage#129]

**Comment by witchica** [comment]
It's going to be in the next update! I've been working on modelling and texture ideas for it for a while, happy to finally be able to do it!

**Comment by ardissaps** [comment]
Nice, can't wait!

**Comment by OkinawaGaijin** [comment]
Would you be so kind to add [Trinkets ](https://modrinth.com/mod/trinkets)support as well, so we can equip it additionally to armor?

Loving your mod so far, the ease of use, the flexibility, the space, SPACE!, it's just great. It's one of the mods I didn't think I need until I downloaded it. Now I crafted your backpack and already replaced another backpack mod with it.

**Comment by witchica** [comment]
Yes I'll definitely look into that @OkinawaGaijin :)
