### ISSUE TITLE
Forge version using wrong Block Entity system

### ISSUE THREAD

**Issue by witchica** [deletey/CompactStorage#130]
The Forge version of the mod is utulising the Vanilla system for block entities rather than the capability system implemented by Forge. The inter mod compatibility side of this was fixed in the latest commit and release but the system needs to be rewritten to utilise the Forge version of the system. This rewrite is in progress.

**Comment by EthanZeigler** [comment]
This affects fabric too. Since it's not using the fabric inventory/transfer system, other mods that interact with inventories don't see this mod's blocks as containers. ArchitectuaryAPI might make supporting both easier on you.

**Comment by witchica** [comment]
> This affects fabric too. Since it's not using the fabric inventory/transfer system, other mods that interact with inventories don't see this mod's blocks as containers. ArchitectuaryAPI might make supporting both easier on you.

This actually occured to me today because I was working on something else, trying it out now so hopefully will be fixed soon

**Comment by EthanZeigler** [comment]
Is it possible to backport the fix to 1.19.2? Many, many mods are still stuck there because of the massive changes mojang made to the internals between 1.19.2->1.19.3

**Comment by witchica** [comment]
Ya I'm currently supporting 19.3, 19.2 and 18.2 so all of those have been fixed and are available on curseforge and modrinth as 5.0.3 :)
