### ISSUE TITLE
Villagers cant use Barrel for POI

### ISSUE THREAD

**Issue by xanthian** [deletey/CompactStorage#131]
As above :)

**Comment by witchica** [comment]
It looks like this is something hard coded into Minecraft, the Poi types has it hard coded as Blocks.Barrel, for Fabric I can perhaps do a Mixin to add more but it feels like the type of thing that could break intercompatibility with other mods. Let me look into it and I'll get back to you :)

``` 
PoiTypes.java
      register(p_218083_, FISHERMAN, getBlockStates(Blocks.BARREL), 1, 1);
```

**Comment by witchica** [comment]
For forge this is registerable, needs to be looked at but should be fixed in a commit today

**Comment by xanthian** [comment]
It is doable.
[BetterNether ](https://github.com/quiqueck/BCLib/commit/1628ac9a86c584957a379dcb248be50058ac42d7)has just added the facility.
Friends and Foes has it for [Beehives](https://github.com/Faboslav/friends-and-foes/commit/d418c23b6ca77bd046d82b88ac5950993702e691).

I had it working on my [Grindstones ](https://github.com/xanthian/variant_sticks_and_stuff/blob/1.18_archive/src/main/java/net/xanthian/vsas/mixin/PointOfInterestTypeMixin.java)and [Barrels ](https://github.com/xanthian/variantbarrels/blob/1.18_archive/src/main/java/net/xanthian/variantbarrels/mixin/PointOfInterestTypeMixin.java)in 1.18 but can no longer get it working in 1.19
Hidden reason for raising the issue, wondered how you may do it 😋

**Comment by witchica** [comment]
> It is doable. [BetterNether ](https://github.com/quiqueck/BCLib/commit/1628ac9a86c584957a379dcb248be50058ac42d7)has just added the facility. Friends and Foes has it for [Beehives](https://github.com/Faboslav/friends-and-foes/commit/d418c23b6ca77bd046d82b88ac5950993702e691).
> 
> I had it working on my [Grindstones ](https://github.com/xanthian/variant_sticks_and_stuff/blob/1.18_archive/src/main/java/net/xanthian/vsas/mixin/PointOfInterestTypeMixin.java)and [Barrels ](https://github.com/xanthian/variantbarrels/blob/1.18_archive/src/main/java/net/xanthian/variantbarrels/mixin/PointOfInterestTypeMixin.java)in 1.18 but can no longer get it working in 1.19 Hidden reason for raising the issue, wondered how you may do it 😋

Interesting! I'll take a look more into it, I started a new job this week so time has been tight!

**Comment by witchica** [comment]
Here is how I've got it working https://github.com/tabithastrong/compact-storage/blob/fabric/src/main/java/com/tabithastrong/compactstorage/CompactStorage.java#L126 seems to work okay in my testing so will see how it goes with players

**Comment by xanthian** [comment]
Interesting, so doesn't even need mixin now. 🤯

**Comment by witchica** [comment]
> Interesting, so doesn't even need mixin now. 🤯

I've used an access widener as I don't see the need for a Mixin, I could be wrong so just hoping no new bugs come out of it! The 1.19 version was bugged so is being re-released now

**Comment by witchica** [comment]
Unfortunately impossible in Forge 1.19 because the PoiType is a record, this should also not work on Fabric but for some reason it seems happy so I'm just going to hope it keeps working!
