### ISSUE TITLE
Remove server log entry (FABRIC)

### ISSUE THREAD

**Issue by Darkwolf202** [deletey/CompactStorage#132]
Everytime a backpack (haven't tried with a chest) is opened, the attached pops up in the server logs/thread

![image](https://user-images.githubusercontent.com/57463653/181432046-164a4201-9632-4e6f-b3b7-0e72386fd493.png)

Is there a way to turn this off so as not to clog up the logs?

**Comment by witchica** [comment]
Fixed in 5.0.2 for [1.18.2](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3903530) and [1.19](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3903532). Thanks for reporting :)
