### ISSUE TITLE
关于1.7.10的tabithastrong

### ISSUE THREAD

**Issue by SGDKaFei** [deletey/CompactStorage#134]
我现在想要做1.7.10tabithastrong的新贴图以及适应不同大小的背包与箱子 但是需要作者1.7.10的源代码

**Comment by witchica** [comment]
Can you please explain a bit more about what you want to do?

**Comment by SGDKaFei** [comment]
我想要不同的容量适配不同的贴图 例如3*4的背包适配一个贴图 12*16的箱子适配一个贴图
但是现在我3*9的箱子跟背包适配的都是同一个贴图 就算是容量变化也一样

**Comment by witchica** [comment]
Ah I getcha, unfortunately I don't think the source is kicking about anymore. The earliest that is on Github is 1.18.2 at the moment. I will take a look for you and get back

**Comment by SGDKaFei** [comment]
十分感谢！我期望你 能给我带来好消息

**Comment by witchica** [comment]
Unfortunately the source appears to be gone, I've looked over GitHub and through files but I do not have it anymore. Sorry about that
