### ISSUE TITLE
Barrels & Chests missing block tags

### ISSUE THREAD

**Issue by xanthian** [deletey/CompactStorage#135]
Vanilla Barrel
![image](https://user-images.githubusercontent.com/7688001/182112378-e17c5032-970f-4720-b614-a9d998994b9d.png)

Compact Storage Barrel
![image](https://user-images.githubusercontent.com/7688001/182112421-ab6d8560-a117-41e4-8bbd-3163eb0e1704.png)

Vanilla Chest
![image](https://user-images.githubusercontent.com/7688001/182112784-1fb9b15a-6a00-470a-ae53-754889769254.png)

Compact Storage Chest
![image](https://user-images.githubusercontent.com/7688001/182112856-0cc2b00c-186a-45aa-9bca-8274c9cae751.png)

Important one being mineable/axe as currently the chests and barrels take a long time to break.

**Comment by witchica** [comment]
I'll get on this, as for the breaking they should be mineable/pickaxe so not sure why that hasn't popped on - I'll get that one sorted :-) I am on vacation right now so will be in a few days time before it gets sorted

**Comment by witchica** [comment]
@xanthian Have added these tags on for the next release
![image](https://user-images.githubusercontent.com/3160169/183246415-d117943a-83d1-4094-87ba-e9a84ed079fe.png)

**Comment by xanthian** [comment]
why pickaxe may I ask :)

**Comment by witchica** [comment]
Feel like it is better fitting with the iron recipe of the chests

**Comment by witchica** [comment]
This update will be pushed soon but is currently on the backburner due to a family emergency. Will be back soon to get this wrapped up.

**Comment by witchica** [comment]
new versions for [forge](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3951029) and [fabric](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3951012) with block tags now out.
