### ISSUE TITLE
[bug] Dupe bug 

### ISSUE THREAD

**Issue by CKY-** [deletey/CompactStorage#136]
Using a thermal crescent hammer on any chest or barrel results in duplicating. 
https://www.curseforge.com/minecraft/mc-mods/thermal-expansion 

thermal_expansion-1.18.2-1.6.3.13

compact_storage-5.0.1-1.18.2

**Comment by witchica** [comment]
this will be fixed in a new build tomorrow

**Comment by CKY-** [comment]
thank you :D

**Comment by witchica** [comment]
There we go, versions pushing up to Curseforge now as 5.0b2-LTS
