### ISSUE TITLE
Backpack contents was overwritten from others (Different from #137))

### ISSUE THREAD

**Issue by Aleon4201** [deletey/CompactStorage#138]
I have 4 backpacks - orange, black, purple, and light blue.
Purple was overwritten by Black's contents by the following operations. Btw, width and height aren't.

1. Put Black into a hotbar (in this case, 8).
2. Open Black.
3. Put Purple into the hotbar(8) by pressing "8" key from any inventory. (Blacks is still opening!)
4. Close it (maybe Black).
5. Open Purple from its hotbar.

Version: 1.16.5-5.1b17

**Comment by witchica** [comment]
I can't replicate this behaviour in 1.19.3 so I am guessing somewhere between 1.16.5 and 1.19.3 this got fixed, I will look into updating this for 1.16.5 as it is breaking behaviour. Thank you for your detailled steps. I will look into and if I need any more info will get back to you

**Comment by witchica** [comment]
I no longer have the source for 1.16.5 so unfortunately this cannot be fixed

**Comment by Aleon4201** [comment]
Oh, that's bad...
But don't worry, I'm updating my own mod pack to 1.19.2 (or 1.19.3 when all mods I want are updated to it) now, and mainly playing 1.18.2.
