### ISSUE TITLE
Server crashed with Exception ticking world Caused by: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by ColdTearsYY** [deletey/CompactStorage#139]
1.19.2 fabric

latest.log:https://paste.ubuntu.com/p/scJ3wqqCVv/
crash report:https://paste.ubuntu.com/p/CYjrQyMyrV/

use compact_storage_fabric-5.0_lts_b2_1.19.2

**Comment by witchica** [comment]
This might be more of a fabric issue as I don't see a direct refernce to CompactStorage, let me have a look but for now I'd suggest trying a different version of Fabric
