### ISSUE TITLE
add Config

### ISSUE THREAD

**Issue by O2theC** [deletey/CompactStorage#140]
Idea:
add config to limit the max size of chests, etc
this way if people feel the default is too op they can change it to be lower, say 5 height and 20 width or something
or if they want to go crazy, they could make it go higher to 100 by 100 or something, prob going to need to change GUI for that tho,
either way, a config to change the max width and height of chest, barrels, and backpacks would be nice/useful, making them individual,  could be a nice touch too.

I will admit that I do not make mods, I understand if this is not possible or too hard to do, all I ask is that you tell me such
have a great day.

**Comment by witchica** [comment]
This is something that used to be in the mod, max size 24x12 but lowerable in a configuration file. I am quite new to Fabric so was trying to get it working in both Forge and Fabric before realeasing it out. As for bigger than 24x12, that is in the works and will be out hopefully soon

**Comment by shap-po** [comment]
+1 here, also not sure if you meant to close the issue as it was not implemented
