### ISSUE TITLE
 fill level display with Jade !!!

### ISSUE THREAD

**Issue by AsunaNiechan** [deletey/CompactStorage#142]
Unfortunately, the Compact Storage Mod v5.0-lts-b2_1.19.2 in connection with Jade v8.7.0 1.19.2 has problems with the fill level display. The boxes that have more than 165 slots only show 162 (10.36k) and the rest is ignored

**Comment by witchica** [comment]
I will look into this however I Imagine that it might be a limitaiton of the way Jade looks at the NBT, will let you know
