### ISSUE TITLE
Request: View contents

### ISSUE THREAD

**Issue by Soggyshorts** [deletey/CompactStorage#144]
Great mod, thank you!

Is there any way to make this work with 

https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip

So I can see inside bags?

Cheers

**Comment by Soggyshorts** [comment]
nvm, user error

**Comment by witchica** [comment]
I will certainly take a look as that looks really intriguing, I was also planning on looking into adding bigger shulker boxes
