### ISSUE TITLE
loading screen rewind error

### ISSUE THREAD

**Issue by Rogenar** [deletey/CompactStorage#145]
compact_storage_fabric-5.0.1_1.19.3 version is faulty. The mod is causing the game to fail to start. the loading screen rewinds.

**Comment by witchica** [comment]
Can you please provide a log file?

**Comment by Rogenar** [comment]
[rei.log](https://github.com/tabithastrong/compact-storage/files/10451575/rei.log)
[rei-issues.log](https://github.com/tabithastrong/compact-storage/files/10451576/rei-issues.log)
[latest.log](https://github.com/tabithastrong/compact-storage/files/10451577/latest.log)

**Comment by witchica** [comment]
I'd suggest removing the mod and giving it a retry, looks like the file may be corrupted.

**Comment by Rogenar** [comment]
I tried but I encountered the same error again.

**Comment by witchica** [comment]
I have just updated to 5.0.2 to fix a bug, can you try this version?

**Comment by Rogenar** [comment]
I am facing the same error in version 5.0.2. loading screen keeps rewinding

**Comment by witchica** [comment]
Does your game crash or does it just keep rewinding until it closees? If it doesnt actually crash try leaving it for longer and upload that log file

**Comment by witchica** [comment]
Another thing that I could ask is can you try just Compact Storage and Fabric with no other mods to see if this issue still occurs

**Comment by Rogenar** [comment]
the game keeps rewinding until it closes

**Comment by Rogenar** [comment]
[rei.log](https://github.com/tabithastrong/compact-storage/files/10451962/rei.log)
[rei-issues.log](https://github.com/tabithastrong/compact-storage/files/10451963/rei-issues.log)
[latest.log](https://github.com/tabithastrong/compact-storage/files/10451964/latest.log)

**Comment by witchica** [comment]
Can you try with just Fabric and CompactStorage for me?

**Comment by Rogenar** [comment]
I tried with Fabric and CompactStorage and got the same error again. this time a single text document is created in the logs section. 
[latest.log](https://github.com/tabithastrong/compact-storage/files/10456660/latest.log)
