### ISSUE TITLE
One bag copied contents onto another bag

### ISSUE THREAD

**Issue by Soggyshorts** [deletey/CompactStorage#146]
I had 4 bags in my action bar and was scrolling between them when one bag had its entire contents overwritten by another.
Sadly it was my bag of crap stuff that got duplicated and I've lost 100s hours of gathering and looting.

**Comment by witchica** [comment]
Which version of the mod are you using? Sorry to hear that, its been a wee issue for a while but it should have been fixed in the latest version. Were they in your main hotbar?

**Comment by Soggyshorts** [comment]
We're on 1.19.2 so I'm using compact_storage_fabric-5.0_lts_b2_1.19.2
Yes, both bags were in my main hotbar, the far right one got copied onto the one next to it

**Comment by witchica** [comment]
This bug should have been fixed in the latest release which is [compact_storage_fabric-5.0.1_1.19.2.jar
](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352575). Let me know if you have any more issues with it :)
