### ISSUE TITLE
Tooltip Offset

### ISSUE THREAD

**Issue by mrfishy14** [deletey/CompactStorage#149]
![image](https://user-images.githubusercontent.com/92015626/219846888-40c2c281-40bb-4d60-934c-73ebda487e19.png)
As you can see the tool tip inside the compact barrel has an offset from the item in the middle, listed are all installed mods:
{
3dskinlayers fabric 1.5.2 mc1.19.1 
Adorn 3.8.1+1.19.2 fabric 
advancednetherite fabric 1.6.6 1.19.2 
alternate current mc1.19 1.4.0 
animatica 0.5+1.19 
another furniture fabric 2.1.2 1.19.2 
antighost 1.19.1 fabric0.58.5 1.1.5 
architectury 6.5.69 fabric 
areas 1.19.2 4.1 
ArmorPoser fabric 1.19.2 1.2.1 
axolotl item fix 1.1.4 
BambooEverything fabric 2.2.4 build.33+mc1.19.2 
BasicShields 1.4.0 1.19.2 
bclib 2.1.6 
better end 2.1.4 
better nether 7.1.3 
BetterAdvancements Fabric 1.19.2 0.2.2.142 
BetterAnimationsCollection v4.0.5 1.19.2 Fabric 
BetterBlockOutline 1.5.1 1.19 
BetterF3 4.0.0 Fabric 1.19.2 
betterfpsdist fabric 1.19 2.4 
betterlily 
bettermounthud 1.2.0 
bettersafebed fabric 1.19 4 
betterspawnercontrol 1.19.2 4.0 
betterstats 2.2.1+1.19.2 
betterthanmending 1.3.0 
BetterThirdPerson Fabric 1.19 1.9.0 
BetterTridents v4.0.2 1.19.2 Fabric 
blockus 2.5.6+1.19.2 
boathud 1.1.2 
Bookshelf Fabric 1.19.2 16.2.17 
boosted brightness 2.1.2+1.19 
borderless mining 1.1.5+1.19 
BotanyPots Fabric 1.19.2 9.0.27 
BotanyTrees Fabric 1.19.2 5.0.4 
BowInfinityFix 1.19.x fabric 2.5.0 
bushierflowers 0.0.1 1.19.2 
Capes 1.4.5+1.19 
carpet extra 1.19.2 1.4.84 
carpet fixes 1.19 1.12.2 
cem 0.7.1 
chalk 2.1.0+1.19 
charm fabric 1.19.2 4.4.4 
CITResewn 1.1.2+1.19.2 
cloth config 8.2.88 fabric 
collective 1.19.2 6.45 
colormatic 3.1.2+mc.1.19 
comforts fabric 6.0.3+1.19.2 
compact storage fabric 5.0.3 1.19.2 
Companion 1.19.2 fabric 3.2.1 
configured fabric 2.0.0 1.19.2 
continuity 2.0.1+1.19 
convenientdecor 0.1.0 
CreativeCore FABRIC v2.9.3 mc1.19.2 
CreaturesFromTheSnow 4.1.0+1.19.2 
creeper firework 1.19.2 1.4.0 
Croptopia 1.19.2 FABRIC 2.2.2 
ctov 3.1.4 
culinaryconstruct fabric 5.0.0 beta.1+1.19.2 
cullclouds 0.1.0 
CullLessLeaves 1.0.6 
dark loading screen 1.6.12 
DarkKore 0.3.0 1.19 
dashloader 4.1.3+1.19 
dcch 1.2 
Debugify 2.8.0 
Decor bound 1.1 [1.19.2] 
decor4fabric 1.2.1 
Decorative Blocks fabric 1.19.2 3.0.0 
deeperdarker fabric 1.1.6 fabric 
deepslatecutting fabric 1.5.0 
DiagonalFences v4.2.3 1.19.2 Fabric 
Display Case fabric 1.19 1.0.3 
duckling 2.0.8 fabric 
dynamic fps 2.2.0 
EasyAnvils v4.0.6 1.19.2 Fabric 
ecologics fabric 1.19.2 2.1.11 
effective 1.4 
elytraslot fabric 6.1.0+1.19.2 
enhancedblockentities 0.7.2+1.19.2 
entityculling fabric 1.5.2 mc1.19 
Essential fabric 1 19 
everycomp 1.19.2 2.2.2 fabric 
exlinefurniture fabric 1.19.2 v2.3.2 
fabric api 0.73.2+1.19.2 
fabric carpet 1.19.2 1.4.84+v221018 
fabric language kotlin 1.9.1+kotlin.1.8.10 
fabric tree chopper 0.8.10 
FabricShieldLib 1.6.1 1.19 
fabricskyboxes 0.6.2+mc1.19.2 
fabrishot 1.9.1 
farsight fabric 1.19 2.4 
Fastload+1.19.2 2.6.11 
ferritecore 5.0.3 fabric 
findme 3.1.0 fabric 
flowers and mooblooms 1.0.0 
ForgeConfigAPIPort v4.2.10 1.19.2 Fabric 
freecam 1.1.6+1.19 
FriendlyFire Fabric 1.19.2 14.0.1 
fsb interop 1.1.3+mc1.19.2 build.25 
furnitureexpanded 1.0.2 1.19.2 FABRIC 
Galosphere 1.19.2 1.2.2 Fabric 
geckolib fabric 1.19 3.1.39 
glassdoor 3.0.0+1.19 
handcrafted fabric 1.19.2 2.0.2 
harvestwithease 1.19.2 4.0.0.3 fabric 
HealthOverlay 1.19.2 7.2.3 
HopoBetterUnderwaterRuins 1.19 1.1 
HorseExpert v4.0.0 1.19.2 Fabric 
ImmediatelyFast 1.1.8+1.19 
indium 1.0.9+mc1.19.2 
InventoryProfilesNext fabric 1.19 1.9.2 
iris mc1.19.2 1.5.2 
item model fix 1.0.3+1.19 
ItemPhysic FABRIC v1.6.6 mc1.19.2 
jamlib 0.6.0+1.19 
jecalculation fabric 1.19.2 4.0.2 
jei 1.19.2 fabric 11.5.2.1007 
jei 1.19.2 fabric 11.6.0.1010 
JustEnoughResources Fabric 1.19.2 1.2.1.189 
lambdabettergrass 1.3.0+1.19 
lambdynamiclights 2.2.0+1.19.2 
lapisreserve 1.0.8 
lazydfu 0.1.3 
libIPN fabric 1.19 2.0.2 
libraryferret fabric 1.19.2 3.0.0 
litematica fabric 1.19.2 0.12.6 
lithium fabric mc1.19.2 0.10.4 
loadmyresources fabric 1.0.4 MC 1.19 1.19.2 
lovely snails 1.1.0+1.19 
macawsbridgesbyg fabric 1.19.2 1.0 
main menu credits 1.1.1 
malilib fabric 1.19.2 0.13.0 
mavapi 1.0.1 mc1.19.2 
mavm 1.2.0 mc1.19.2 
mcw bridges 2.0.6 mc1.19.2fabric 
mcw doors 1.0.8fabric mc1.19.2 
mcw fences 1.0.7 mc1.19.2fabric 
mcw lights 1.0.5 mc1.19.2fabric 
mcw paintings 1.0.4fabric mc1.19.2 
mcw paths 1.0.2fabric mc1.19.2 
mcw roofs 2.2.2 mc1.19.2fabric 
mcw trapdoors 1.0.8 mc1.19.2fabric 
mcw windows 2.1.2 mc1.19.2fabric 
mcwfencesbyg fabric 1.19.2 1.0 
memoryleakfix 1.19.3 0.7.0 
midnightcontrols 1.7.4+1.19 
midnightlib fabric 1.0.0 
minelib11 0.1.3+1.19 
minihud fabric 1.19.2 0.23.3 
MixinConflictHelper 1.2.0 
mixintrace 1.1.1+1.17 
modmenu 4.1.2 
moonlight 1.19.2 2.2.7 fabric 
more geodes 1.6.4+1.19 
morechathistory 1.19.1 1.1.1 
morefrogs 1.19.x 1.2.3b fabric 
MouseTweaks fabric mc1.19 2.22 
mvs 2.5.10 1.19.2 
name visibility 1.0.0 
naturalist fabric 2.1.1 1.19.2 
NoChatReports FABRIC 1.19.2 v1.13.12 
nofade 1.18 2.0.1 
Notes 1.19.2 2.0.0 fabric 
Oaks Decor v9.0 IndoorFurniture (Fabric) (PUBLIC) 
Oh The Biomes You'll Go fabric 1.19.2 2.0.0.13 
open parties and claims fabric 1.19.2 0.16.6 
optigui 1.1.6 
oxidized 1.7.2 
Paintings fabric 1.19.2 10.2.4.0 
paladin furniture mod 1.1.1 fabric mc1.19 
Ping Wheel 1.2.0 fabric 1.19.2 
plushie mod 1.2 
polymorph fabric 0.46.1+1.19.2 
puzzle 1.4.0 1.19 
PuzzlesLib v4.3.12 1.19.2 Fabric 
quartz elevator 2.1.5+1.19 
red bits 1.14.1 
reeses sodium options 1.4.9+mc1.19.2 build.67 
resolution control plus 1.19.x 3.0.0 
right click harvest 3.1.0+1.19 1.19.2 
satin 1.9.0 
servercore 1.3.3 1.19.2 
show me your skin 1.3.7+1.19 
shroomdealers 1.6 1.19.2 fabric 
simplebackup 1.3.7 
simplefog 1.3.1 
smoothboot fabric 1.19 1.7.1 
Sod 22.10.13 MC1.17x to 1.19.x 
sodium extra 0.4.16+mc1.19.2 build.90 
sodium fabric mc1.19.2 0.4.4+build.18 
sodium shadowy path blocks 3.1.0 
soundphysics fabric 1.19.2 1.0.18 
sriaflowersv2.0.1 1.19.2 
starlight 1.1.1+fabric.ae22326 
Strawgolem fabric 1.19.2 2.0.0 beta.5 
Structory 1.19 v1.3 
supplementaries 1.19.2 2.2.49 fabric 
TerraBlender fabric 1.19.2 2.0.1.130 
the bumblezone fabric 6.6.8+1.19.2 
toofast 1.19 1.0.0 
transparent 5.1.2+1.19 fabric 
trinkets 3.4.2 
veinmining fabric 1.0.2+1.19.2 
villagernames 1.19.2 5.1 
waveycapes fabric 1.3.2 mc1.19.2 
windchimes 1.2.1 
wolf armor compat 1.0.3 1.19.2 
wolves with armor 1.8.0 1.19 
woof 3.0.0 1.19 
XaerosWorldMap 1.28.9 Fabric 1.19.1 
Xaeros Minimap 23.1.0 Fabric 1.19.1 
xp storage 1.4.3+1.19 
YetAnotherConfigLib 2.2.0 for 1.19.2 
yosbr 0.1.1 
YungsApi 1.19.2 Fabric 3.8.2 
YungsBetterDesertTemples 1.19.2 Fabric 2.2.1 
YungsBetterDungeons 1.19.2 Fabric 3.2.1 
YungsBetterMineshafts 1.19.2 Fabric 3.2.0 
YungsBetterOceanMonuments 1.19.2 Fabric 2.1.0 
YungsBetterStrongholds 1.19.2 Fabric 3.2.0 
YungsBetterWitchHuts 1.19.2 Fabric 2.1.0 
YungsExtras 1.19.2 Fabric 3.1.0 
Zoomify 2.9.0 
z mcwroofsbyg fabric 1.19.2 1.1 
}

**Comment by witchica** [comment]
Odd! I will investigate
