### ISSUE TITLE
Chest Builder Duplicating

### ISSUE THREAD

**Issue by Advyy** [deletey/CompactStorage#150]
Hi, I just downloaded compact storage to a custom pack and my friends and I have ran into a bug where when we place down the chest builder it doesn't remove from our inventories and can be placed down however many times and broken. The chunk also dies and a internal server error is thrown and nobody can go into the chunk after. The server needs to be restarted for people to join back. After i removed the chest builder it was fine. 
[06:18:06] [Server thread/INFO]: [net.minecraft.world.WorldServer:bridge$createSnapshot:4942]: java.lang.NullPointerException
[06:18:06] [Server thread/INFO]: COMPACTSTORAGE DATA DUMP: breakBlock()

**Comment by witchica** [comment]
What version is this on? Chest builder hasn't been in the mod for ages

**Comment by Advyy** [comment]
1.12.2, due to the server having fossils and archelogy

**Comment by witchica** [comment]
1.12.2 had a lot of issues, try [ComPatchedStorage](https://www.curseforge.com/minecraft/mc-mods/compatchedstorage)
