### ISSUE TITLE
Maxed Compact Chest not compatible with Simple Storage Network.

### ISSUE THREAD

**Issue by ZeroKaion** [deletey/CompactStorage#151]
The inventory is not fully detected by Tom's Simple Storage mod. When connected to a network some items won't show up. I'm using the fabric version of Compact Storage 5.0.3 and Tom's Simple Storage 1.5.6.

**Comment by loukaso** [comment]
I'm having the same problem. The issue extends also to item pipes from other mods e.g. Industrial Revolution and Modern Dynamics - items won't be pumped into slots past the 54th slot; seems like the inventory is registered as having only 54 slots (the default compact barrel/chest size) even when upgraded. Interestingly the problem only arises after the world/server has been reset after the inventory has already been placed in the world - if you mine it and place it back down then it behaves as expected until the world is reloaded again - so it feels like a problem with the initial entity registration when the world is loaded.

Version 5.0.3 Fabric 1.19.2

**Comment by CKY-** [comment]
Woks great on Forge,

**Comment by witchica** [comment]
Think this may be an issue with the inventory size and how fabric handles that, i'll take a look and see if i can find a way to fix it :)

**Comment by Elatax** [comment]
Is there any news here for a fix?

**Comment by kurisubrooks** [comment]
Also having this issue. Let me know if there's anything I can help with to help debug the issue.
