### ISSUE TITLE
Compact Storage 1.20.1-5.1.2 Crash When Trying To Open Chest

### ISSUE THREAD

**Issue by yancypro** [deletey/CompactStorage#153]
I created a Chest then placed it down and tried to open it. That's when the game crashed. See the attached crash report and please notify me when it is repaired so I can update my version. I was playing the 1.20.1-5.1.2 version on a 1.20.2 game because the mod hasn't been updated to 1.20.2 yet but it loaded fine.
Thanks for this mod Jessica. I really don't want to play Minecraft without it.

[crash-2023-11-12_12.40.40-server CompactStorage Fault.txt](https://github.com/witchica/compact-storage/files/13328726/crash-2023-11-12_12.40.40-server.CompactStorage.Fault.txt)

**Comment by yancypro** [comment]
Also crashes when opening Backpacks. See attached crash report.

[crash-2023-11-12_13.15.06-server CompactStorage Backpack Fault.txt](https://github.com/witchica/compact-storage/files/13328760/crash-2023-11-12_13.15.06-server.CompactStorage.Backpack.Fault.txt)

**Comment by witchica** [comment]
This is because the class being used there has been moved, the mod needs updating for that version of the game. Currently in progress with a generic update to both the Fabric and Forge versions :)
