### ISSUE TITLE
Storage options incompatible w/ Hey That's Mine

### ISSUE THREAD

**Issue by kvietcong** [deletey/CompactStorage#155]
Looking into the code it seems that the storage options added w/ this mod don't extend `LockableObject` (`com.github.fabricservertools.htm.api.LockableObject`) which is required by [Hey That's Mine](https://modrinth.com/mod/htm/version/1.1.5) (a storage locking server mod). Extended Storage, another storage mod seems to have done it (https://github.com/QuiltServerTools/HeyThatsMine/issues/16) [like this](https://gitlab.com/Compass_System/expanded-storage/-/blob/1.20/fabric/src/main/java/compasses/expandedstorage/impl/mixin/common/HTMLockableBlockEntityCompat.java#L5,15).

Is there any way this mod could implement this functionality? Thanks!

**Comment by witchica** [comment]
Sure! I can look into that!
