### ISSUE TITLE
Column and Row are incorrectly labeled/swapped?

### ISSUE THREAD

**Issue by kurisubrooks** [deletey/CompactStorage#156]
In v5.0.3 Fabric (1.20.1) - it appears that the Row and Column upgrade items have incorrect/swapped names. I keep making the wrong upgrades and incorrectly screwing up my chests because of it 😅 

I checked my configs folder to see if it could be an issue caused by the modpack devs (I'm using BigChadGuys Plus v1.1.7), but there doesn't appear to be a config file for this mod.

For context, the game locale is the default one (en_US).

![image](https://github.com/witchica/compact-storage/assets/6291467/f2171c48-c082-4f90-a024-d08d6cdf4187)
![image](https://github.com/witchica/compact-storage/assets/6291467/cfefbed5-f7c2-4086-9105-7f81b767ec43)

**Comment by witchica** [comment]
Feel like this was me being a bit silly when updating stuff, its on my list!
