### ISSUE TITLE
Create mod brass funnel potentially not detecting chest upgrades? 

### ISSUE THREAD

**Issue by Lesuu** [deletey/CompactStorage#157]
I made a sorting system using create on my server, the modpack that i'm using (BCG+ 1.1.9, which uses fabric version 5.0.3 of compact storage) has both create and compact storage. The sorting system uses brass funnels with filters and a mechanical arm and fills up compact storage chests. When the chests were "too full", they would stop being able to receive items regardless of over half of the storage space being free. Once I upgraded the chests again, they "unclogged". I dont know why or when it happened, but it didnt seem to happen earlier on when I was playing, which means it must've broken at some point. I tried restarting the server too, which didn't help. It seemed to me as if the funnel was reading the chest as being full even when it wasnt. Maybe it wasnt counting the upgrades? I'm not quite sure. 

The screenshot was the limit of items i was able to put in. Removing one stack would let the funnel add one more stack, and it was able to add to existing stacks. 
![2024-01-15_22 53 31](https://github.com/witchica/compact-storage/assets/122235588/2a7db0c1-ed76-4a82-9bef-7d45b35cc353)

A screenshot of the sorting system. Each brass funnel is attached to a chest and the mechanical arm picks up items from the belt and sorts them automatically, according to filters (the problem didnt come from filters as even without any filters the funnel would refuse to take items in).
![2024-01-15_22 53 13](https://github.com/witchica/compact-storage/assets/122235588/39547199-18a1-4a8c-bc18-b3704df1d3c9)

**Comment by kurisubrooks** [comment]
Possibly related to https://github.com/witchica/compact-storage/issues/151#issuecomment-1687578060

**Comment by witchica** [comment]
My main guess for this is it is initializing with 9 x 6 and not passing on that update to other blocks, shall investigate and update :)
