### ISSUE TITLE
[Bug] Chests duplicate with any block-rotating wrench OR using /setblock.

### ISSUE THREAD

**Issue by SonyStinks** [deletey/CompactStorage#158]
Found the closed Bug #136 where chests duplicate using Thermal wrenches.  This issue is still happening with EnderIO's Yeta wrench, Supplementaries' wrench, and, as far as I can tell, EVERY OTHER WRENCH that rotates generic blocks.

It also duplicates simply by using `/setblock` and changing the `facing=` parameter, though you have to add the tags manually in the command to keep the original chest's properties, of course.

Forge mod loader was used. I won't speak for the Fabric mod version, but if it happens with vanilla commands, then most likely Fabric is affected also.

Some (hopefully) helpful info:

- Mod version: 5.1.2-1.20.1
- Java version: 18.0.1.1, Oracle Corporation
- Forge version: 47.2.19
- OS: Ubuntu Linux 22.04 LTS
- Minecraft version 1.20.1

To reproduce:
1) Make a chest from this mod.
2) Place it in the world.
3) Either:
     A) make a wrench that rotates vanilla blocks and use it on the chest, or 
     B) use `/setblock` to change the `facing=` parameter.

I use it to make more maxed-out chests as needed....but I shouldn't be able to do that.

**Comment by witchica** [comment]
Okay interesting, shall take a look at this as it likely affects both fabric and forge.
