### ISSUE TITLE
Toms Simple Storage fix

### ISSUE THREAD

**Issue by craftercis** [deletey/CompactStorage#160]
Hello,

Would it be possible to make a fix so that the fully upgraded chests work with Toms's Simple Storage mod?

**Comment by witchica** [comment]
Yeah this will be fixed with similar bugs :)

**Comment by craftercis** [comment]
Hey again. I saw the new update. Is it possible for you to have a version that also works with 1.20.1. Then it will work with the BigChadGuys Plus modpack :D

Edit: I read just now the commit :D. So only the 1.20.1 question is still up :D

**Comment by craftercis** [comment]
Hey sorry for the tag but is there a reason that there is no backwards support for this update? @witchica

**Comment by witchica** [comment]
> Hey sorry for the tag but is there a reason that there is no backwards support for this update? @witchica

Hiya, focusing right now on updates to 1.20.4 and then if the fix works as expected will get backported
