### ISSUE TITLE
Mod Compatibility: Simple Storage Mod blocks do not connect to the storage system

### ISSUE THREAD

**Issue by logosexnihilo** [deletey/CompactStorage#165]
**Repro steps:**

1. Launch Minecraft with Forge, Simple Storage Network, and Compact Storage
2. Via Creative/Survival, obtain any Compact Chest
3. Connect it to the Simple Storage Network system with the item import cable

**Results:**
Simple Storage Network does not recognize the storage, stopping the player from using it as storage

**Additional Notes:** 
* **Compact Storage will connect to Simple Storage after connecting the cables and then exiting and rejoining the world.**
* Repro rate: 10/10
* Minecraft version: 1.20.1
* Forge version: 47.2.0
* Simple Storage Network version: 1.20.1-1.10.0
* Compact Storage version: 1.20.1-forge-6.0.1.64

https://github.com/witchica/compact-storage/assets/43560919/537f5afa-04e8-485c-92d6-78f84243e0ab

**Comment by witchica** [comment]
I'm not managing to replicate this behaviour at all, I have

- SimpleStorageNetwork 1.10.0
- Forge 47.2.0
- CompactStorage 6.0.1.64

https://github.com/witchica/compact-storage/assets/3160169/a94595b4-b362-4c2f-9d14-fe484806d76c

**Comment by F-a-y-t-h** [comment]
Bit of a necro but the issue happens only when the chests/barrels are upgraded.

also effects other inventory reading mods like tom's storage and crafting station

![image](https://github.com/witchica/compact-storage/assets/14098907/bee42e94-f383-4238-9e67-98f9b0d43da9)

Forge//compact-storage-1.20.1-forge-6.0.1.64.jar

**Comment by witchica** [comment]
> Bit of a necro but the issue happens only when the chests/barrels are upgraded.
> 
> also effects other inventory reading mods like tom's storage and crafting station
> 
> ![image](https://private-user-images.githubusercontent.com/14098907/330334752-bee42e94-f383-4238-9e67-98f9b0d43da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzgzNDgsIm5iZiI6MTcxNTY3ODA0OCwicGF0aCI6Ii8xNDA5ODkwNy8zMzAzMzQ3NTItYmVlNDJlOTQtZjM4My00MjM4LTllNjctOThmOWIwZDQzZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Njc0ZWY1ODhlYThhZWM3MWM4NDkwNDI3ZmY4ZDY3OTRmZTE3YWU4NDgzNTQ2ODQ0YjhiY2RkYzcxMGExZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.efYOsyZEpIzdQ91KTCweY9EzGLTCpoP2sHmrkg_8g2k)

what version of the mod and which modloader is this?
