### ISSUE TITLE
Dying Chests

### ISSUE THREAD

**Issue by LTAxe42** [deletey/CompactStorage#166]
If you have items in a chest and you put a dye on it it removes all the items that are in the chest.

**Comment by witchica** [comment]
what version

**Comment by witchica** [comment]
If it is any 6.0 version, the CurseForge page does state
6.0 Fabric, Forge and NeoForge 1.20.1 and 1.20.4

    Chest / Barrel contents are removed when dying to a different colour, please update to 6.1
