### ISSUE TITLE
Duping Drums

### ISSUE THREAD

**Issue by MSandro** [deletey/CompactStorage#167]
Compact Storage 6.2.0.65
NeoForge 20.4.223

if I break a Drum they are dropping it self two times.

**Comment by witchica** [comment]
I shall take a look~!

**Comment by MSandro** [comment]
yes please, I can still reproduce the issue.

**Comment by witchica** [comment]
Fixed with https://github.com/witchica/compact-storage/commit/15ebbc1c27e10088aa0e28c8e68a93bce7855115 and will be release soon
