### ISSUE TITLE
Inventory deleted

### ISSUE THREAD

**Issue by DynuKin** [deletey/CompactStorage#168]
So, not sure why, but when dyeing a compact storage chest (I ended up doing this accidentally not realising dye was selected on my hotbar) it deletes it's entire inventory and upgrades. I was just right clicking to go store stuff and poof it changed colour and everything was gone. This seems like an oversight more then anything else and I couldn't find if this was changed on different versions, but I thought I would at least post about it in case it hasn't been reported at all. 

I would suggest preventing the dye from being usable on already placed chests if nothing else works well

compact-storage-1.20.1-fabric-6.0.1.62.jar this is the name of the file for the version I am using

**Comment by witchica** [comment]
So as per Curseforge

6.0 Fabric, Forge and NeoForge 1.20.1 and 1.20.4

    Chest / Barrel contents are removed when dying to a different colour, please update to 6.1
