### ISSUE TITLE
Fabric 1.20.1 version doesn't work

### ISSUE THREAD

**Issue by Romans96** [deletey/CompactStorage#172]
Hello! I'm just trying to use CompactSTorage6 with Fabric 1.20.1, (fabric api 0.92.0).
I Tried to run minecraft with only fabric api and compact storage and with my full current modpack.
In both case it crashes.
This is the compactStorage verison i'm using: https://modrinth.com/mod/compact-storage/versions?l=fabric&g=1.20.1

These are the crash reports:
- This is the crash report with only compact storage and fabric-api 0.92.0-1.20.1:
[crash-2024-05-25_01.03.10-client.txt](https://github.com/witchica/compact-storage/files/15440720/crash-2024-05-25_01.03.10-client.txt)

- This is the crash report with my current modpack (with compactStorage disabled it works):
[crash-2024-05-25_01.06.36-client.txt](https://github.com/witchica/compact-storage/files/15440723/crash-2024-05-25_01.06.36-client.txt)

**Comment by witchica** [comment]
This is my mistake! That version is a 1.20.4 version, must not have uploaded the 1.20.1 to Modrinth. Here you go! https://modrinth.com/mod/compact-storage/version/iaFSn2o9
