### ISSUE TITLE
Rows and columns are reversed in the storage upgrade items

### ISSUE THREAD

**Issue by blinloo** [deletey/CompactStorage#173]
"Storage Upgrade (+1 Row)" item increases an inventory's width instead of its height.
Similarly with the "Storage Upgrade (+1 Column)" increasing the height.

This should be the other way round as columns are vertical and rows are horizontal.
Swapping the names of the items and descriptions should fix the issue.

Or honestly just changing the items to "+1 Width"/"+1 Height" respectively to avoid confusion altogether since the storage items themselves only lists height and width, not rows and columns.

Version in use: compact-storage-1.20.1-fabric-6.0.1.64

**Comment by witchica** [comment]
That change has been implemented in the 1.20.4+ versions, thought I had already backported it too but I guess not. It's on my list! :)

**Comment by blinloo** [comment]
Ahh, thanks for letting me know :3
Sorry for not checking in the newer versions I should have before posting, my bad! >.<

**Comment by witchica** [comment]
No worries at all!! :) I’ll backport it at some point !!
