### ISSUE TITLE
Consider Using New Inventory Capabilities

### ISSUE THREAD

**Issue by Darkosto** [deletey/CompactStorage#65]
Hello!

I would like to use your mod in my upcoming modpack, however, it seems to not integrate well with other mods due to an incompatibility. Would you be willing to add the new Inventory Capabilities system into CompactStorage to allow a much wider range of cross-mod integration?

"CapabilityItemHandler#ITEM_HANDLER_CAPABILITY"

MC: 1.12.2
Forge: 2760
CompactStorage:3.1

Thank you and please let me know if I can answer any more questions. Have a great rest of your day!
Darkosto

**Comment by tobystrong** [comment]
Yep gotta do this, been on a break - will look into having it sorted soon

**Comment by Lothrazar** [comment]
Any updates on this? :)  Would be a big help to connect these to other mods

**Comment by witchica** [comment]
Fixed in https://github.com/deletey/CompactStorage/commit/cba0432c51d85f5d40c272ba9dbd5d02d9bcfe88
