### ISSUE TITLE
Chest Builder crash

### ISSUE THREAD

**Issue by Mac15001900** [deletey/CompactStorage#70]
Crash log: https://pastebin.com/fMjLKaFX

I got a crash apparently caused by TileEntityChestBuilder. It happened shortly after I started feeding the Chest Builder with chests by a vanilla hopper. My guess is that it probably happened after 64 of them have been supplied. 
I was trying to make a maximum sized chest.

When trying to reload the world, the same crash instantly happens again.

Minecraft version: 1.12.2
Forge version: 14.23.5.2831
Mod version: 3.1
Modpack: Sky Factory 4, without any mod changes

**Comment by RazAssassin** [comment]
was this in a singleplayer world? or on a server?

**Comment by Mac15001900** [comment]
It was on singleplayer.

**Comment by witchica** [comment]
There's an issue with hoppers, I'll be fixing this within the next 24 hours or so

**Comment by witchica** [comment]
Fixed in https://github.com/deletey/CompactStorage/commit/cba0432c51d85f5d40c272ba9dbd5d02d9bcfe88
