### ISSUE TITLE
Not being able to craft Compact Chests

### ISSUE THREAD

**Issue by DeltaOmegaTV** [deletey/CompactStorage#72]
I was trying to make a storage system and when i went to make a compact chest in the chest builder it will not work it either spits my items back at me or they stay in it and when i click build nothing happens

**Comment by Kennox** [comment]
We have the some problem on our SkyFactory 4 server. Cannot craft any chests (didnt try backpacks), just hearing a ding sound when i press build.

**Comment by DeltaOmegaTV** [comment]
Yep its really annoying that its not working for an unknown reason

**Comment by kestryll** [comment]
SF4 server here too. wont craft the chests

**Comment by DeltaOmegaTV** [comment]
what hosts are yall using?

**Comment by kestryll** [comment]
i just host my own server for me and a few of my friends on my desktop

**Comment by DeltaOmegaTV** [comment]
i have a company server for it and that means it should be a issues in the mod for servers.

**Comment by kestryll** [comment]
yea, i just tested it in a singleplayer world and it works just fine. gotta be a server problem

**Comment by kestryll** [comment]
just looked on twitch and the latest update to SF4 included a mod update for ComPatchedStorage possibly the issue but i obviously have no clue

**Comment by DeltaOmegaTV** [comment]
> just looked on twitch and the latest update to SF4 included a mod update for ComPatchedStorage possibly the issue but i obviously have no clue

the mod that you use to craft the chests in CompactStorage though

**Comment by kestryll** [comment]
right, but both Waila and JEI show it as ComPatchedStorage

**Comment by DeltaOmegaTV** [comment]
true

**Comment by kestryll** [comment]
@DeltaOmegaTV i have found a fix. all i had to do was manually update the ComPatchedStorage mod to the latest update on both the client and server. once i did that i was able to create the CompactStorage chests no problem

**Comment by DeltaOmegaTV** [comment]
how did you update it though?

**Comment by kestryll** [comment]
since i have the sever on my own pc, i downloaded the lastest mod and replaced it in the server files. and the same for the client by going into the files that twitch created. if you dont have access to the server files it wont work unfortunately

**Comment by Kennox** [comment]
> @DeltaOmegaTV i have found a fix. all i had to do was manually update the ComPatchedStorage mod to the latest update on both the client and server. once i did that i was able to create the CompactStorage chests no problem

Ohh great, I will try that as soon as possible and will report back!

**Comment by RobinNightWing** [comment]
Yeah I'm having the same issue, but it seems as tho that Sky Factory has the newest version of this mod. I'll also try reinstalling

**Comment by RobinNightWing** [comment]
Also same issue happens with backpacks

**Comment by Kennox** [comment]
Update to 'ComPatchedStorage-1.12.2-1.5.1' and it works now! SkyFactory 4 had the 1.4.1 version.

**Comment by witchica** [comment]
This will be fixed. I wish that I had been contacted instead of someone making a patch mod.
