### ISSUE TITLE
Items in Chest Disappearing Visual Bug

### ISSUE THREAD

**Issue by bcrotty** [deletey/CompactStorage#73]
Whenever I put an item in my Compact Chest, the item visually disappears until I leave the chest and reopen it. If I have multiple items in there and I pick up one of them, all the other items seem to disappear until I reopen the chest.

**Comment by witchica** [comment]
Can you confirm whether you're using SkyFactory 4?

**Comment by Shadows-of-Fire** [comment]
This bug was only ever introduced by Compatched, so yes, he is.

**Comment by bcrotty** [comment]
Yes, that's right.

**Comment by witchica** [comment]
Ok well I guess it's fixed for now.
