### ISSUE TITLE
[1.12.2] Compact Storage and Thermal Expansion bug

### ISSUE THREAD

**Issue by ImMineOfficial** [deletey/CompactStorage#80]
When you connect a Itemduct cable from Thermal Expansion to a chest builder it crashes the server. I've accidentally connected the Itemduct cable to the chest builder while I had connected the cable with the compact chest. All other things are in the crash log. Hopefully there is a fast bugfix that I can play on the server :D

Here is the crash report: https://paste.labymod.net/golunovedi.sql

**Comment by Bikecicle** [comment]
I have the exact same issue. In addition to itemducts, it occurs with vanilla hoppers.

Crash report for hoppers: https://pastebin.com/Jpuv8vw2

**Comment by NeuralNotW0rk** [comment]
Installing ComPatchedStorage resolved the issue for me: https://www.curseforge.com/minecraft/mc-mods/compatchedstorage
