### ISSUE TITLE
Backpack bug 

### ISSUE THREAD

**Issue by GogetaBlue427** [deletey/CompactStorage#82]
I ran into an issue with the backpack for 1.15.2 with the newest update for forge of the mod, 
Forge 1.15.2 v4.0.3. I have 3 backpacks crafted and renamed one of the backpacks for convenience using the anvil, also have all 3 on the quickbar slots. I left the game and came back, but one of the unnamed backpacks inventory was wiped and was exactly the same as the named backpack, no crashes or errors though.

**Comment by witchica** [comment]
This seems so strange, I'll have to investigate
