### ISSUE TITLE
Server fails to open whenever I try to open it

### ISSUE THREAD

**Issue by ghost** [deletey/CompactStorage#83]
Posted this issue somewhere else, this is what they said.

> > Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2618
> 
> Which is `ChestAnimationProgress` This is a special case since you have to tell loader to only implement it on the client using:
> 
> ```java
> @EnvironmentInterfaces(@EnvironmentInterface(
>     value = EnvType.CLIENT,
>     itf = ChestAnimationProgress.class
> ))
> ```
> 
> This is because it is a client only interface.
> 
> So it's a mod issue, which you should contact the author about

**Comment by witchica** [comment]
This is getting fixed in the next release, I'll update here when it's released
