### ISSUE TITLE
Chest not being treated as a chest

### ISSUE THREAD

**Issue by Chrisjohnson57387** [deletey/CompactStorage#93]
Howdy. The compact chests aren't able to receive items from hoppers or pipes as a regular or some other modded chests would.

Playing version 1.16.5-5.0.1

**Comment by witchica** [comment]
I'll have a look into this as they have the capability so that's very odd, have you tried item pipes or similar from other mods? If those work then I might know the issue

**Comment by VoiidInVaiin** [comment]
Can confirm! i've tried using hoppers, item pipes from various mods (cyclic,quark,refined pipes, silents mechanism) none work.

**Comment by witchica** [comment]
Fixed! https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3196221
