### ISSUE TITLE
Crash when accidental right-clicking chest or barrel with bottle in hand

### ISSUE THREAD

**Issue by Chrisjohnson57387** [deletey/CompactStorage#98]
When right clicking on a barrel with a bottle in my hand, the game crashes. I did a reload a few times and the issue is consistent; also tested with chest.
Got this error, lines 2 & 3 repeat for a long long time:

1: java.lang.StackOverflowError: Unexpected error
2: 	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
3:	at me.tobystrong.compactstorage.block.tile.BaseTileEntity.getCapability(BaseTileEntity.java:65) ~[compactstorage:5.0] {re:classloading}

**Comment by witchica** [comment]
Can you try the new version on Curseforge if not using already, it says 1.16.5 but should work on .4 too

**Comment by Chrisjohnson57387** [comment]
Works!
