### ISSUE TITLE
Server crash while user is putting items inside the backpack

### ISSUE THREAD

**Issue by Varijon** [deletey/CompactStorage#99]
Haven't narrowed down exactly when it happens, but the user was actively swapping items in the backpack. Size didn't seem to matter.

https://gist.github.com/Varijon/c184296bc74fd6883b537f34867fad30

Version:
compactstorage-1.16.5-5.1.2.jar
forge-1.16.5-36.0.22.jar

Edit:
Looking at the code it seems related to saving the backpack data on close. The person in this situation has a slight bit of lag, if that affects anything.

**Comment by Varijon** [comment]
This error happened again when a player had their backpack empty when trying to upgrade, then relogged and the server crashed with the same error.

**Comment by witchica** [comment]
I'll take a dive into this tomorrow and get back to you :)

**Comment by GeekJokes** [comment]
i came here to find out, i was between this, building gadgets (the item that i was transferring) and akashic tome, which was mentioned in the log for whatever reason

**Comment by witchica** [comment]
https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/3209571 should fix it, any issues let me know tho
